language: php

sudo: false

cache:
    directory:
        - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_script:
  - composer install --prefer-dist -n --no-progress

script:
  - phpunit --coverage-text

