language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/dependency-injection:${SYMFONY_VERSION}; fi;

install:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-text

